monobank:
  endpoint: https://api.monobank.ua

cache:
  expireTime: 300000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}